sudo: required
dist: trusty
services:
  - docker

before_install:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build -d
  - docker ps

script:
  - docker ps
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run web bin/rake db:create db:migrate
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run web bundle exec rspec
