version: '3'

services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 9001:3000
    depends_on:
      - redis
  redis:
    image: redis
