version: '3'

services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 9001:3000
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    env_file: .env.web
  redis:
    image: redis
  postgres:
    image: postgres:9.6
    volumes:
      - ./db/data:/var/lib/postgres/data
    env_file: .env.postgres
