version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    links:
      - postgres
    environment:
      RAILS_ENV: test
  postgres:
    image: postgres:9.6
    volumes:
      - ./db/data:/var/lib/postgresql/data
